mod 'puppet-nginx', '3.3.0'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-concat'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker'
mod 'puppetlabs-apt'
mod 'puppetlabs-powershell'
mod 'puppetlabs-pwshlib'
mod 'puppetlabs-reboot'
